### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by willnode** [domcloud/domcloud#18]
I wish I can work to improve the service but currently got have no time so this is a reminder to me.

Things to complete in order:
+ [ ] [Template generator](https://github.com/domcloud/dom-template-generator)
  + [X] UI (in React)
  + [ ] Code Generator
  + [ ] Integrate to portal
+ [x] [Unified rootkit](https://github.com/domcloud/dom-next-rookit)
  + [x] Rewrite existing code to Node.js
  + [X] Write Virtualmin API proxy
  + [X] Write Deploy-to-SSH proxy
  + [X] Integrate to servers
+ [ ] ~[Rewrite portal](https://github.com/domcloud/dom-next-portal)~
  + [ ] ~Rewrite existing code to Node.js (same database layout)~
  + [ ] ~Integrate with GitHub like it's the first-class~
  + [X] Bake template generator and write deploy engine to work with unified rootkit
  + [ ] Custom/self-managed servers with monthly pricing
  + [ ] Move away from CentOS

ETA probably before next year.

**Comment by Aritz331** [comment]
> got have

![image](https://user-images.githubusercontent.com/59333567/181996798-321012f6-c484-4193-a13c-c2ee618b8727.png)

**Comment by willnode** [comment]
This is a very old thread. Gotta update soon.

**Comment by elycheikhsmail** [comment]
@willnode you might need to hire some worker to accelerate this roadmap realeases.
I think domcloud is very interesting for most dev, it will simplify deployement of web app written in language like python, javascript and so on.

**Comment by willnode** [comment]
I wish I can do that. I need to stabilize the cash flow first, as not enough people subscribing currently.

**Comment by willnode** [comment]
We strive to update features quarterly in the blog: https://domcloud.co/blog

Stay tuned also in our Twitter page! https://twitter.com/domcloud_co
